development:
  root_image_url: "http://www.plannto.com/images/"
  no_of_main_item: 1
  no_of_item_in_tab: 10
test:
  root_image_url: "http://www.plannto.com/images/"	
production:
  root_image_url: "http://www.plannto.com/images/"
  no_of_main_item: 1
  no_of_item_in_tab: 10
