defaults:
    namespace: plannto
    sessions: false
    client: dalli
development:
    disabled: true
    servers: localhost:11211
production:
    servers:
      - 127.0.0.1:11211 # Default host and port
    # debug: true
    # memory: 256
    # benchmarking: false
