development:
  bucket: planntodev
  access_key_id: AKIAJWDCN4DJWNL2FK5A
  secret_access_key: 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
  region: us-east-1

test:
  bucket: plannto
  access_key_id: AKIAJWDCN4DJWNL2FK5A
  secret_access_key: 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
  region: us-east-1

production:
  bucket: planntonew
  access_key_id: AKIAJWDCN4DJWNL2FK5A
  secret_access_key: 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
  region: ap-southeast-1