production:
  solr:
    hostname: localhost
    port: 8980
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8980
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8980
    log_level: WARNING