production:
  solr:
    hostname: index.websolr.com
    port: 80
    path: /solr/be892ddc4fb

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING